Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.hostname = "rocky9-jenkins"

  config.vm.network "private_network", ip: "192.168.3.10"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 50000, host: 50000

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.disk :disk, size: "20GB", name: "extra_storage"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "jenkins-lab"
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vbguest.auto_update = false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.inventory_path = "ansible/inventory.ini"
  end
end

