apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-monitor
  namespace: formazione-sou
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-reader
  namespace: formazione-sou
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-reading-binding
  namespace: formazione-sou
subjects:
- kind: ServiceAccount
  name: deployment-monitor
  namespace: formazione-sou
roleRef:
  kind: Role
  name: deployment-reader
  apiGroup: rbac.authorization.k8s.io
